-- what exactly do we mean by trail here is that these are ordered sequences of our partner businesses with a story attached. 
--Trails either human authorized or generated by AI. The story is a narrative that connects the businesses in the trail, and can be used to create a more engaging experience for users.

create table trails ( 
    id    uuid primary key default uuidv7(),
    slug  text not null unique,
    title text not null,
    summary text ,
    status  text not null default 'draft' check (status in ('draft', 'published', 'archived')),
    estimated_minutes int check (estimated_minutes > 0),
    generated_by text not null default 'human' check (generated_by in ('human', 'ai')),
    generated_model text,
    generated_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint trails_published_needs_summary
    check ( status <> 'published' or summary is not null)

);

    create trigger trails_set_updated_at
    before update on trails
    for each row
    execute function set_updated_at();
    

    create table stops( 
        id          uuid primary key default uuidv7(),
        trail_id    uuid not null references trails (id) on delete cascade,
        business_id uuid not null references businesses (id),
        position    int not null check (position > 0),
        deal_headline  text, 
        deal_details   text,
        arrival_hint    text, 
        walk_meters_from_prev int check(walk_meters_from_prev >= 0),
        walk_seconds_from_prev int check(walk_seconds_from_prev >= 0),
        route_computed_at timestamptz,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        
         constraint stops_trail_position_key unique (trail_id, position)
         deferrable initially immediate,
         constraint stops_trail_business_key unique (trail_id, business_id)
    );
    
   
    
    create trigger stops_set_updated_at
    before update on stops
    for each row
    execute function set_updated_at();
   
    create index stops_business_id_idx on stops (business_id);
    
